# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    parameters:
      mname:
        description: "Project module name"
        default: "tabulate-core"
        type: string
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run tests!
      - run: gradle << parameters.mname >>:test
      - store_test_results:
          path: << parameters.mname >>/build/test-results/test

  publishSnapshot:
    parameters:
      mname:
        description: "Project module name"
        default: "tabulate-core"
        type: string
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx6200m
      TERM: dumb
    steps:
      - checkout
      - run: ./import_key.sh $GPG_PRIVATE_KEY $GPG_PUBLIC_KEY $GPG_PRIVATE_KEY_PASSWORD
      - run: gradle -Psigning.gnupg.keyName=$GPG_KEY_ID -Psigning.gnupg.passphrase=$GPG_PRIVATE_KEY_PASSWORD << parameters.mname >>:publishToSonatype

  publishMavenVersion:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx6200m
      TERM: dumb
    steps:
      - checkout
      - run: ./import_key.sh $GPG_PRIVATE_KEY $GPG_PUBLIC_KEY $GPG_PRIVATE_KEY_PASSWORD
      - run: gradle -Psigning.gnupg.keyName=$GPG_KEY_ID -Psigning.gnupg.passphrase=$GPG_PRIVATE_KEY_PASSWORD publishToSonatype closeAndReleaseSonatypeStagingRepository

workflows:
  test:
    jobs:
      - test:
          mname: tabulate-core
  publishSnapshots:
    when:
      equal: [ "publish_snapshot", << pipeline.parameters.GHA_Meta >> ]
    jobs:
      - publishSnapshot:
          mname: tabulate-core
      - publishSnapshot:
          mname: tabulate-csv
      - publishSnapshot:
          mname: tabulate-excel
  publishMavenVersion:
    when:
      equal: [ "publish_release", << pipeline.parameters.GHA_Meta >> ]
    jobs:
      - hold:
          type: approval
      - publishMavenVersion:
          requires:
            - hold