name: Set Next Version

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Set next version'
        required: false
        default: ''
jobs:
  setNextVersion:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set Next Version
        run: gradle markNextVersion -Prelease.customPassword=${GITHUB_TOKEN} -Prelease.customUsername=${GITHUB_ACTOR} -Prelease.version=${NEXT_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ github.event.inputs.nextVersion }}
      - name: Publish Snapshot
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        with:
          GHA_Meta: "publish_snapshot"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}